module.exports = grammar({
    name: 'ic10',

    extras: $ => [$._whitespace],

    word: $ => $.identifier,

    rules: {
        source_file: $ => alias(repeat($.line), $.program),

        line: $ => seq(
            optional(choice($.instruction, $.label)),
            optional($.comment),
            $.newline,
        ),

        label: $ => seq($.identifier, ':'),

        newline: $ => choice('\n', '\r\n', '\r'),

        _whitespace: $ => /[ \t]+/,

        comment: $ => seq(
            /#.*/
        ),

        instruction: $ => seq(
            field('operation', choice($.operation, alias($.identifier, $.invalid_instruction))),
            repeat(field('operand',
                $.operand
            ))
        ),

    // Elevate STR/HASH functions to highest precedence and list before identifier/logictype to avoid partial matches.
    operand: $ => choice(
        $.str_function,
        $.hash_function,
        $.register,
        $.device_spec,
        $.number,
        $.logictype,
        $.identifier
    ),

        identifier: $ => /[a-zA-Z_.][a-zA-Z0-9_.]*/,

        register: $ => token(prec(5,choice(
            'ra',
            'sp',
            seq(
                repeat1('r'),
                /[0-9]|1[0-5]/
            )
        ))),

        network_index: $ => /[0-9]+/,

        device_spec: $ => seq(
            $.device,
            optional(
                seq(
                    ":",
                    $.network_index,
                )
            )
        ),

        device: $ => token(prec(5,seq(
            'd',
            choice(
                'b',
                /[0-5]/,
                seq(
                    repeat1('r'),
                    /[0-9]|1[0-5]/
                )
            ),
        ))),

        _constant: $ => choice(
            'nan',
            'pinf',
            'ninf',
            'pi',
            'deg2rad',
            'rad2deg',
            'epsilon',
        ),

        preproc_string: $ => /[^"\n]*/,

        // Parse HASH("...") as a proper function call with child nodes
        hash_function: $ => seq(
            field('function', alias(token(prec(15, /HASH/i)), $.hash_keyword)),
            '(',
            field('argument', alias(token(/"[^"\n]*"/), $.hash_string)),
            ')'
        ),

        // Parse STR("...") as a proper function call with child nodes  
        str_function: $ => seq(
            field('function', alias(token(prec(15, /STR/i)), $.str_keyword)),
            '(',
            field('argument', alias(token(/"[^"\n]*"/), $.str_string)),
            ')'
        ),

        number: $ => choice(
            token(
                choice(
                    seq(
                        optional('-'),
                        /[0-9]+/,
                        optional(seq(
                            '.',
                            /[0-9]+/
                        ))
                    ),
                    seq("%", /[01_]+/),
                    seq("$", /[0-9a-fA-F_]+/),
                ),
            ),
            $._constant
        ),

        operation: $ => choice(
            'l',
            's',
            'ls',
            'lr',
            'sb',
            'lb',
            'alias',
            'move',
            'add',
            'sub',
            'sdse',
            'sdns',
            'slt',
            'sgt',
            'sle',
            'sge',
            'seq',
            'sne',
            'sap',
            'sna',
            'and',
            'or',
            'xor',
            'nor',
            'mul',
            'div',
            'mod',
            'j',
            'bltz',
            'bgez',
            'blez',
            'bgtz',
            'bdse',
            'bdns',
            'bnan',
            'bnan',
            'brnan',
            'lbn',
            'lbns',
            'lbs',
            'lr',
            'not',
            'sbn',
            'sbs',
            'sla',
            'sll',
            'sra',
            'srl',
            'snan',
            'snanz',
            'ss',
            'beq',
            'bne',
            'bap',
            'bna',
            'jal',
            'brdse',
            'brdns',
            'bltzal',
            'bgezal',
            'blezal',
            'bgtzal',
            'beqal',
            'bneal',
            'jr',
            'bdseal',
            'bdnsal',
            'brltz',
            'brgez',
            'brlez',
            'brgtz',
            'breq',
            'brne',
            'brap',
            'brna',
            'sqrt',
            'round',
            'trunc',
            'ceil',
            'floor',
            'max',
            'min',
            'abs',
            'log',
            'exp',
            'rand',
            'yield',
            'label',
            'peek',
            'push',
            'pop',
            'hcf',
            'select',
            'blt',
            'bgt',
            'ble',
            'bge',
            'brlt',
            'brgt',
            'brle',
            'brge',
            'bltal',
            'bgtal',
            'bleal',
            'bgeal',
            'bapal',
            'bnaal',
            'beqz',
            'bnez',
            'bapz',
            'bnaz',
            'breqz',
            'brnez',
            'brapz',
            'brnaz',
            'beqzal',
            'bnezal',
            'bapzal',
            'bnazal',
            'sltz',
            'sgtz',
            'slez',
            'sgez',
            'seqz',
            'snez',
            'sapz',
            'snaz',
            'define',
            'sleep',
            'sin',
            'asin',
            'tan',
            'atan',
            'cos',
            'acos',
            'atan',
            'get',
            'getd',
            'put',
            'putd',
            'atan2',
            'bdnvl',
            'bdnvs',
            'clr',
            'clrd',
            'ext',
            'ins',
            'ld',
            'lerp',
            'poke',
            'pow',
            'rmap',
            'sd',
        ),

        logictype: $ => token(prec(5,choice(
            // Basic status
            'Power',
            'Open',
            'Mode',
            'Error',
            'Lock',
            'Activate',
            'On',
            'Idle',
            'Setting',
            // Pressure & Temperature
            'Pressure',
            'Temperature',
            'PressureExternal',
            'PressureInternal',
            'PressureSetting',
            'TemperatureSetting',
            'TemperatureExternal',
            // Power
            'PowerPotential',
            'PowerActual',
            'PowerGeneration',
            'PowerRequired',
            'RequiredPower',
            // Gas ratios
            'Reagents',
            'RatioOxygen',
            'RatioCarbonDioxide',
            'RatioNitrogen',
            'RatioPollutant',
            'RatioVolatiles',
            'RatioWater',
            'RatioNitrousOxide',
            'RatioHydrogen',
            'RatioPollutedWater',
            'RatioSteam',
            // Liquid ratios
            'RatioLiquidOxygen',
            'RatioLiquidNitrogen',
            'RatioLiquidCarbonDioxide',
            'RatioLiquidPollutant',
            'RatioLiquidVolatiles',
            'RatioLiquidNitrousOxide',
            'RatioLiquidHydrogen',
            // Input gas ratios
            'RatioOxygenInput',
            'RatioCarbonDioxideInput',
            'RatioNitrogenInput',
            'RatioPollutantInput',
            'RatioVolatilesInput',
            'RatioWaterInput',
            'RatioNitrousOxideInput',
            'RatioLiquidOxygenInput',
            'RatioLiquidNitrogenInput',
            'RatioLiquidCarbonDioxideInput',
            'RatioLiquidPollutantInput',
            'RatioLiquidVolatilesInput',
            'RatioLiquidNitrousOxideInput',
            'RatioSteamInput',
            // Input2 gas ratios
            'RatioOxygenInput2',
            'RatioCarbonDioxideInput2',
            'RatioNitrogenInput2',
            'RatioPollutantInput2',
            'RatioVolatilesInput2',
            'RatioWaterInput2',
            'RatioNitrousOxideInput2',
            'RatioLiquidOxygenInput2',
            'RatioLiquidNitrogenInput2',
            'RatioLiquidCarbonDioxideInput2',
            'RatioLiquidPollutantInput2',
            'RatioLiquidVolatilesInput2',
            'RatioLiquidNitrousOxideInput2',
            'RatioSteamInput2',
            // Output gas ratios
            'RatioOxygenOutput',
            'RatioCarbonDioxideOutput',
            'RatioNitrogenOutput',
            'RatioPollutantOutput',
            'RatioVolatilesOutput',
            'RatioWaterOutput',
            'RatioNitrousOxideOutput',
            'RatioLiquidOxygenOutput',
            'RatioLiquidNitrogenOutput',
            'RatioLiquidCarbonDioxideOutput',
            'RatioLiquidPollutantOutput',
            'RatioLiquidVolatilesOutput',
            'RatioLiquidNitrousOxideOutput',
            'RatioSteamOutput',
            // Output2 gas ratios
            'RatioOxygenOutput2',
            'RatioCarbonDioxideOutput2',
            'RatioNitrogenOutput2',
            'RatioPollutantOutput2',
            'RatioVolatilesOutput2',
            'RatioWaterOutput2',
            'RatioNitrousOxideOutput2',
            'RatioLiquidOxygenOutput2',
            'RatioLiquidNitrogenOutput2',
            'RatioLiquidCarbonDioxideOutput2',
            'RatioLiquidPollutantOutput2',
            'RatioLiquidVolatilesOutput2',
            'RatioLiquidNitrousOxideOutput2',
            'RatioSteamOutput2',
            // Pressure/Temperature inputs/outputs
            'PressureInput',
            'TemperatureInput',
            'TotalMolesInput',
            'PressureInput2',
            'TemperatureInput2',
            'TotalMolesInput2',
            'PressureOutput',
            'TemperatureOutput',
            'TotalMolesOutput',
            'PressureOutput2',
            'TemperatureOutput2',
            'TotalMolesOutput2',
            // Combustion
            'Combustion',
            'CombustionInput',
            'CombustionInput2',
            'CombustionOutput',
            'CombustionOutput2',
            'CombustionLimiter',
            // Efficiency & Performance
            'EnvironmentEfficiency',
            'WorkingGasEfficiency',
            'OperationalTemperatureEfficiency',
            'TemperatureDifferentialEfficiency',
            'PressureEfficiency',
            'Efficiency',
            // Position & Velocity
            'PositionX',
            'PositionY',
            'PositionZ',
            'VelocityMagnitude',
            'VelocityRelativeX',
            'VelocityRelativeY',
            'VelocityRelativeZ',
            'VelocityX',
            'VelocityY',
            'VelocityZ',
            'ForwardX',
            'ForwardY',
            'ForwardZ',
            'Orientation',
            // Targeting
            'TargetX',
            'TargetY',
            'TargetZ',
            'TargetSlotIndex',
            'TargetPadIndex',
            'TargetPrefabHash',
            // Solar/Angle
            'Horizontal',
            'Vertical',
            'SolarAngle',
            'HorizontalRatio',
            'VerticalRatio',
            'SolarIrradiance',
            // Quantities & Ratios
            'Quantity',
            'TotalQuantity',
            'MaxQuantity',
            'Maximum',
            'Minimum',
            'Ratio',
            'TotalMoles',
            'Volume',
            'VolumeOfLiquid',
            // Import/Export
            'ImportQuantity',
            'ImportSlotOccupant',
            'ExportQuantity',
            'ExportSlotOccupant',
            'ImportCount',
            'ExportCount',
            'ExportSlotHash',
            'ImportSlotHash',
            // Plants
            'Plant',
            'Harvest',
            'PlantHealth1',
            'PlantHealth2',
            'PlantHealth3',
            'PlantHealth4',
            'PlantGrowth1',
            'PlantGrowth2',
            'PlantGrowth3',
            'PlantGrowth4',
            'PlantEfficiency1',
            'PlantEfficiency2',
            'PlantEfficiency3',
            'PlantEfficiency4',
            'PlantHash1',
            'PlantHash2',
            'PlantHash3',
            'PlantHash4',
            'Mature',
            'Seeding',
            'Growth',
            'Health',
            // Recipes & Hashes
            'RecipeHash',
            'RequestHash',
            'PrefabHash',
            'NameHash',
            'CelestialHash',
            'CelestialParentHash',
            // Miscellaneous
            'Color',
            'Charge',
            'ChargeRatio',
            'CompletionRatio',
            'ClearMemory',
            'Output',
            'Filtration',
            'AirRelease',
            'ForceWrite',
            'SignalStrength',
            'SignalID',
            'SettingInput',
            'SettingOutput',
            'CurrentResearchPodType',
            'ManualResearchRequiredPod',
            'MineablesInVicinity',
            'MineablesInQueue',
            'NextWeatherEventTime',
            'Fuel',
            'ReturnFuelCost',
            'CollectableGoods',
            'Time',
            'Bpm',
            'Throttle',
            'Rpm',
            'Stress',
            'InterrogationProgress',
            'ElevatorSpeed',
            'ElevatorLevel',
            'ReferenceId',
            'BestContactFilter',
            // Size
            'SizeX',
            'SizeY',
            'SizeZ',
            'Size',
            // Watts/Contacts
            'MinimumWattsToContact',
            'WattsReachingContact',
            // Slot types
            'Occupied',
            'OccupantHash',
            'Damage',
            'Class',
            'PressureWaste',
            'PressureAir',
            // Batch modes
            'Average',
            'Sum',
            // Channels
            'Channel0',
            'Channel1',
            'Channel2',
            'Channel3',
            'Channel4',
            'Channel5',
            'Channel6',
            'Channel7',
            // Misc
            'Contents',
            'Required',
            'Recipe',
            'StackSize',
            'SoundAlert',
            // Orbital mechanics
            'Acceleration',
            'Altitude',
            'Apex',
            'AutoLand',
            'AutoShutOff',
            'BurnTimeRemaining',
            'Chart',
            'ChartedNavPoints',
            'ContactTypeId',
            'CurrentCode',
            'Density',
            'DerivativeGain',
            'DestinationCode',
            'Discover',
            'DistanceAu',
            'DistanceKm',
            'DrillCondition',
            'DryMass',
            'Eccentricity',
            'EntityState',
            'Extended',
            'FlightControlRule',
            'Flush',
            'Inclination',
            'Index',
            'IntegralGain',
            'LineNumber',
            'Mass',
            'MinedQuantity',
            'NavPoints',
            'NetworkFault',
            'OrbitPeriod',
            'PassedMoles',
            'Progress',
            'ProportionalGain',
            'ReEntryAltitude',
            'Reset',
            'Richness',
            'SemiMajorAxis',
            'Setpoint',
            'Sites',
            'Survey',
            'TemperatureDifferentialEfficiency',
            'Thrust',
            'ThrustToWeight',
            'TimeToDestination',
            'TrueAnomaly',
            'Weight',
            'AlignmentError',
        )))
    }
});
